source 'https://github.com/CocoaPods/Specs.git'

target 'DRYUtilities', :exclusive => true do
  pod "DRYUtilities", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DRYUtilities", :path => "../"

  pod "OCHamcrest", "~> 4.1.1"
  pod "OCMockito", "~> 1.4.0"
end
